apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ template "helm-prometheus-pve-exporter.fullname" . }}
  labels:
    app: {{ template "helm-prometheus-pve-exporter.name" . }}
    chart: {{ template "helm-prometheus-pve-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: "Opaque"
stringData:
  pve.yml: |-
    default:
        user: {{ .Values.pve.name }}
        password: {{ .Values.pve.password }}
        verify_ssl: {{ .Values.pve.ssl }}