name: Release Charts

on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Get Version
        id: get_version
        # You may pin to the exact commit or the version.
        # uses: battila7/get-version-action@90eb8fc70f6dfcf3f9b95ed8f164d2c05038e729
        uses: battila7/get-version-action@v2.2.1
      
      - name: Helm Publisher
        # You may pin to the exact commit or the version.
        # uses: stefanprodan/helm-gh-pages@f1701eb82e4d4b82016e7965501c8b6d79feaec9
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          # GitHub token
          token: "${{ secrets.GITHUB_TOKEN }}"
          # Set the version on the chart to this version
          chart_version: ${{ steps.get_version.outputs.version-without-v }}
